hash=['food','trending',
 'trendingvideo',
 'latestvideo',
 'viralvideo',
 'trendingtopic',
 'trendingcomedy',
 'trendingsong',
 'viral',
 'trendingone',
 'viralone',
 'followme',
 'viralvideos',
 'likeme',
 'like4like',
 'latesttiktok',
 'viraltiktok',
 'trendingtiktok',
 'latestvideos',
 'trendingclip',
 'trendy  ',
 'best',
 'bestvideo',
 'besttiktok',
 'bestcomedy',
 'lovemeorhateme',
 'titktok4fun',
 'fun4tiktok',
 'comedy',
 'topmostfun',
 'fun4u',
 'funforyou',
 'thisis4u',
 'loveyoutiktok ',
 'thisone',
 'happisttiktok',
 'fashiontend',
 'lookatme',
 'im4u',
 'iamforyou',
 'bestvideoforyou  ',
 'top',
 'topvideo',
 'totrending',
 'topvideoontiktok',
 'toptrendiingvideo',
 'toptiktok',
 'tiktoktopmostvideo',
 'videoontop',
 'myvideoontop',
 'feature',
 'featureme',
 'featurethis',
 'tikok_india',
 'Tiktokindia',
 'Indiatiktok',
 'topindiatiktok',
 'featuremy',
 'topcontent',
 'topmost',
 'musically  ',
 'thisisforyou',
 '4upage',
 'foryourpage',
 'video4u',
 'ossamvideo',
 'fun',
 'comedywithfun',
 'bestvideo4u',
 'tiktokbestvideo',
 'mostviraltiktok',
 'tiktokvieo4u',
 'love4u ',
 'popular',
 'popularvideo',
 'mybestvideo',
 'myvideo',
 'bestestvideo',
 'Popularontiktok',
 'mybestie',
 'bestvideoontiktok ',
 'foryou',
 'feature',
 'comedy',
 'prank',
 '15svines',
 'tiktok',
 'featurethis',
 'trending',
 'tiktok_india',
 'loveyou ',
 'dosti',
 'deepfateh ',
 'suit',
 'foryoupage',
 'relationship',
 'acting',
 '1millionaudition',
 'blooper',
 'comedyindia',
 '1mincomedy',
 'edutok',
 'testbook',
 'education',
 'learn',
 'knowledge',
 'learning',
 'mindpower',
 'educationalbusiness',
 'Morden_Education ',
 'speakingenglish ',
 'iterviewtipss',
 'naukri ',
 'careergoals',
 'edutoklifetips',
 'trend',
 'politics',
 'mathmagic',
 'speach',
 'quiz',
 'topper',
 'punjabisongs',
 'tiktokpunjab',
 'musically_new_songs',
 'foryou',
 'viral',
 'new',
 'songs',
 'slowmo',
 'tiktok',
 'duetwithme ',
 'tiktok_India',
 'newsong ',
 'marjaava',
 'shootmode',
 'tiktokflam',
 'music',
 'ranjeetbawa',
 'new_trending',
 'UdictionaryMagic',
 'viralvideo',
 'MooMoodTingTongTwist ',
 'inspirational',
 'edutokmotivation',
 'shayari',
 'madewithme',
 'motivationalvideo',
 'feacherthis',
 'talk',
 'feacherme',
 'livemorechallenge',
 'cleanindia ',
 'edutok',
 'myvoice ',
 'poetry',
 'teamnawab',
 'tiktokgallery',
 'BigBillionAnthem',
 'wrong',
 'decison',
 'life',
 'clear',
 'niece',
 'babygirl',
 'cute',
 'bachha',
 'nephew',
 'doll',
 'savechild',
 'onlychild',
 'childhood',
 'childcomedy',
 'child4child',
 'childact',
 'thischild',
 'children',
 'golden_child',
 'childstar',
 'friendshipgoals',
 'dost',
 'friendshipchallange',
 'friendshipday',
 'friendshiplove',
 'fakefriendship',
 'friendshipforever',
 'happy_friendship_day',
 'truefriendship',
 'friendships ',
 'realfriendship',
 'friendshipbracelets ',
 'internetfriendship',
 'friendship_song',
 'friendshipgoalzz',
 'loveisfriendship',
 'thisfriendshipisover',
 'friendshipbroken',
 'friendshiptest',
 'friendshipg',
 'bestforhealth',
 'forhealt',
 'change',
 'fitness',
 'advice',
 'madinfluence',
 'weightloss',
 'healthtips',
 'edutok',
 'workout',
 'exercise',
 'gym',
 'acupessure  ',
 'homeremedues',
 'tiktokindia',
 'ttfitness',
 'ttsportsmela',
 'healthy',
 'indian',
 'healthiswealth',
 'healthtip',
 'tip',
 'headache',
 'healthylife',
 'stayhealthy',
 'addiction',
 'dancechallenge',
 'danceindia',
 'fingerdance',
 'dancer',
 'danceinpublic',
 'dancelove',
 'dancemasti',
 'DanceKaJungistaan',
 'dancewithkakkar',
 'punchdance ',
 'danceid',
 'dancemom ',
 'dancecover',
 'badboydance',
 'haryanvidance',
 'dancemoves',
 'skeletondance',
 'dancekpop',
 'dancevideo',
 'dancetutorial',
 'myrecipe',
 'newrecipe',
 'esayrecipe',
 'cakerecipe',
 'mysecretrecipe',
 'veganrecipe',
 'recipes',
 'notminerecipe',
 'esayquikrecipe',
 'foodrecipe ',
 'whisperarecipe',
 'breakfastrecipe ',
 'tiktokrecipe',
 'videorecipe',
 'chiritmasrecipe',
 'indianrecipe',
 'madhurasrecipe',
 'homemadrecipe',
 'momsrecipe',
 'vagerecipe',
 'craftchallange',
 'mincraft',
 'crafts',
 'diycraft',
 'crafty',
 'artandcraft',
 'newspapercraft',
 'craftyourlife',
 'craftandart',
 'crafttime ',
 'craftsman',
 'crafting ',
 'easycraft',
 'craftwork',
 'bottlecraft',
 '5_min_craft',
 '5mincraft',
 'sabirmetcraft',
 'airecraft',
 'minecraft',
 'Beautyls',
 'beautychallenge',
 'beautyguru',
 'beautyhacks',
 'naturalbeauty',
 'beautytips',
 'hudabeauty',
 'unlockbeauty',
 'beautyofquetta',
 'beautyfull',
 'sleepingbeauty ',
 'nargisbeauty ',
 'beautyofnature',
 'showyourbeauty',
 'beauty4charity',
 'beautyandthebeast',
 'fabulous_beauty_25',
 'homebeautyhacks ',
 'beautytt',
 'beautyblender',
 'beautyblogger',
 'DanceforBeauty',
 'artchallenge',
 'art02',
 'myart',
 'nailart',
 'artist',
 'isthisart',
 'picsart',
 'creative_art_king',
 'visualart',
 'artwork ',
 'artproject',
 'artik ',
 'workofart',
 'resinart',
 'artmeme',
 'artlover',
 'wallart',
 'chalkart',
 'doodleart',
 'pencilart',
 'festivalfashion',
 'musicfestival',
 'favfestival',
 'marathifestival',
 'festivalseason',
 'festivali',
 's2ofestival',
 'holifestival',
 'mifanfestival',
 'filmfestival? ',
 'festivals',
 'festivalteen ',
 'renaissancefestival',
 'festivalday',
 'mifestival',
 'hindufestival',
 'youthfestival',
 'festivalmode ',
 'pridefestival',
 'festivalfun',
 'rangoliart',
 'myrangoli',
 'rangolichallenge',
 'indolianrangoli',
 'ganeshrangoli',
 'sonarangoli',
 'easyrangoli',
 'rangoliarts',
 'diwalirangoli ',
 'myrangoli',
 'specialrangoli',
 'festivalrangoli ',
 '3drangoli',
 'rangoli_art',
 'rangoli_tiktok_group',
 'rangolimaking',
 'simplerangoli',
 'ran'  ]
all_hashtags=[]
all_view=[]
links=[]
print("scrapping......")
print("scrapping......")
import pandas as pd
import time
from selenium import webdriver
driver = webdriver.Firefox()
for i in hash:
    try:
        driver.get("https://www.tiktok.com/tag/"+str(i))
#     print(driver.page_source)
    except:
        continue
    while True:
        last_height = driver.execute_script("return document.body.scrollHeight")
        data=driver.find_elements_by_xpath('//a[@class="jsx-1229794949 video-feed-item-wrapper"]')
        for link in data:
            l=link.get_attribute("href")
            if l not in links:
                links.append(l)
#                 print(l)
        time.sleep(2)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(6)
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
for i in links:
#     print(i)
    try:
        driver.get(i)
    except:
        continue
    hashtags=driver.find_elements_by_xpath('//a/strong')
    for i in hashtags:
#         print(i.text)
        if i.text not in all_hashtags and i.text!='':
            all_hashtags.append(i.text)
#             print(i.text)

new_hashtags=[]
for i in all_hashtags:
    h=i.split('#')
    try:
        print(h[1])
    except:
        h=i.split('@')
        print(h[1])
    try:   
        driver.get("https://www.tiktok.com/tag/"+str(h[1]))
        time.sleep(6)
        d1=driver.find_elements_by_xpath('//h2[@class="share-sub-title-thin"]')
        for i in d1:
#             print(i.text)
            view=i.text
            all_view.append(view)
            new_hashtags.append("#"+str(h[1]))
#             print("yes")
    except:
        all_view.append("none")
        new_hashtags.append("none")
        continue
if len(new_hashtags)>len(all_view):
    max=len(new_hashtags)
else:
    max=len(all_view)
for i in range(max):
    if i >=len(new_hashtags):
        new_hashtags.append("none")
    if i >=len(all_view):
        all_view.append("none")

df = pd.DataFrame(
    {'hashtags': new_hashtags,'views':all_view})
print(df)

df.to_csv("hashtags.csv", mode='a',encoding='utf-8')